### ISSUE TITLE
Idea Inicial del Reto

### ISSUE THREAD

**Issue by gaagemiliano** [axelgio01/TC1004B.8#1]
El equipo realizará una lluvia de ideas para establecer en lo que se va a trabajar.

**Comment by axelgio01** [comment]
El equipo acordó en hacer una Sistema de Regado Automático para una planta doméstica.
Se guardará paulatinamente la información de la humedad, así como los periodos de regado para mantener registro de las actividades y poder presentar gráficas del mismo.
